version: '3'
services:
  website:
    container_name: blagues_api_dev.fr
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    tty: true
    volumes:
      - .:/app:cached
    env_file:
      - ./.env
    ports:
      - 3000:3000
